server:
  port: 8080


spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://localhost:3306/eztech?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root


okta:
  oauth2:
    issuer: https://dev-487496.okta.com/oauth2/default
    clientId: 0oaj9o7v0G0KcYC1h356
    clientSecret: BdvRx_GAoh7q2EMoHa_BRfZJimC291c0q2h1bTfN
    rolesClaim: groups
