server:
  port: 8080

file:
  root: /Users/lastcow/upload/


spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://localhost:3306/eztech?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  queries:
    users-query: select username, password, active from user where username = ?
    roles-query: select u.username, ur.name from user u right join role ur on (u.role_id = ur.id) where u.username = ?
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


#okta:
#  oauth2:
#    issuer: https://dev-487496.okta.com/oauth2/default
#    clientId: 0oaj9o7v0G0KcYC1h356
#    clientSecret: BdvRx_GAoh7q2EMoHa_BRfZJimC291c0q2h1bTfN
#    rolesClaim: groups
